app/routes.py
from flask import Blueprint, render_template, flash, redirect, request, url_for, session

from app.forms import CompanyForm, EditShareholdersForm
from app.models import Company, Shareholder
from app import db
bp = Blueprint('main', __name__)

@bp.route('/')
def index():
    companies = Company.query.all()
    return render_template('index.html', title='Avaleht', companies=companies)

@bp.route('/add_company', methods=['GET', 'POST'])
def add_company():
    form = CompanyForm()
    if request.method == 'POST':
        print("POST data:", request.form)

    if form.validate_on_submit():
        # todo: this checking should be done in forms
        total_share = 0
        for shareholder_data in form.shareholders.data:
            total_share += shareholder_data.get('share') or 0

        if total_share != form.capital.data:
            flash("Osanike osade summa peab olema võrdne kogukapitaliga.", "danger")
            return render_template('add_company.html', form=form)


        existing_company = Company.query.filter(
            (Company.registry_code == form.registry_code.data) | (Company.name == form.name.data)).first()

        if existing_company:
            if existing_company.registry_code == form.registry_code.data:
                flash(f"Osaühing registrikoodiga {form.registry_code.data} on juba olemas!", "danger")
            elif existing_company.name == form.name.data:
                flash(f"Osaühing nimega {form.name.data} on juba olemas!", "danger")
            return render_template('add_company.html', form=form)

        company = Company(
            name=form.name.data,
            registry_code=form.registry_code.data,
            established_date=form.established_date.data,
            total_capital=form.capital.data,
        )
        db.session.add(company)
        db.session.commit()

        # create shareholders


        for shareholder_data in form.shareholders.data:
            if shareholder_data['is_individual'] == 'individual':
                if not shareholder_data['first_name'] or not shareholder_data['last_name'] or not shareholder_data[
                    'personal_code']:
                    flash("Füüsilise isiku puhul on eesnimi, perekonnanimi ja isikukood kohustuslikud.", "danger")
                    return render_template('add_company.html', form=form)
                elif shareholder_data['is_individual'] == 'legal':
                    # Juriidiline isik
                    if not shareholder_data['company_name'] or not shareholder_data['registry_code']:
                        flash("Juriidilise isiku puhul on nimi ja registrikood kohustuslikud.", "danger")
                        return render_template('add_company.html', form=form)
            shareholder = Shareholder(
                first_name=shareholder_data.get('first_name'),
                last_name=shareholder_data.get('last_name'),
                company_name=shareholder_data.get('company_name'),
                personal_code=shareholder_data.get('personal_code'),
                registry_code=shareholder_data.get('registry_code'),
                share=shareholder_data.get('share'),
                is_founder=True,
                company_id=company.id
            )
            db.session.add(shareholder)



        db.session.commit()

        flash(f'Osaühing "{company.name}" ja osanikud on edukalt lisatud', 'success')
        return redirect(url_for('main.index'))
    else:
        print("Shareholder data after validation:", form.shareholders.data)
        print("Form errors: ", form.errors)
    return render_template('add_company.html', title="Lisa osaühing", form=form)

@bp.route('/company/<int:company_id>')
def company_details(company_id):
    company = Company.query.get_or_404(company_id)
    return render_template('company_details.html', title=company.name, company=company)

@bp.route('/search', methods=['GET', 'POST'])
def search():
    query = request.args.get('q')
    results = []
    if query:
        companies = Company.query.filter(
            (Company.name.ilike(f"%{query}%")) | (Company.registry_code.ilike(f"%{query}%"))
        ).all()

        shareholders = Shareholder.query.filter(
            (Shareholder.first_name.ilike(f"%{query}%")) | (Shareholder.last_name.ilike(f"%{query}%"))
        ).all()

        shareholder_companies = {shareholder.company for shareholder in shareholders}

        # Kombineerime mõlemad tulemused ilma duplikaatideta
        results = list(set(companies).union(shareholder_companies))




    return render_template('search.html', title="Otsingutulemused", results=results, query=query)

@bp.route('/company/<int:company_id>/edit-shareholders', methods=['GET', 'POST'])
def edit_shareholders(company_id):
    company = Company.query.get_or_404(company_id)
    form = EditShareholdersForm()

    if not company:
        flash('Ettevõtet ei leitud.', 'danger')
        return redirect(url_for('main.index'))

    if request.method == 'POST':
        print("POST data:", request.form)


        # Uuendame olemasolevaid osanikke
        for i, shareholder_form in enumerate(form.shareholders):
            shareholder = Shareholder.query.get(shareholder_form.data['id'])
            if shareholder:
                shareholder.share = shareholder_form.data['share']
                shareholder.is_founder = shareholder_form.data['is_founder']

            else:  # Uus osanik
                new_shareholder = Shareholder(
                    first_name=shareholder_form.first_name.data,
                    last_name=shareholder_form.last_name.data,
                    company_name=shareholder_form.company_name.data,
                    personal_code=shareholder_form.personal_code.data,
                    registry_code=shareholder_form.registry_code.data,
                    share=shareholder_form.share.data,
                    is_founder=shareholder_form.is_founder.data,
                    company_id=company_id,
                )
                db.session.add(new_shareholder)

        # Uuendame ettevõtte kogukapitali
        company.total_capital = sum([sh.share for sh in company.shareholders])

        db.session.commit()
        flash('Osanike andmed on edukalt uuendatud!', 'success')
        return redirect(url_for('main.company_details', company_id=company_id))


    # Lisame olemasolevad osanikud vormi
    if not form.shareholders:
        form.shareholders = company.shareholders

    return render_template('edit_shareholders.html', form=form, company=company)

app/templates/add_company.html
{% extends "base.html" %}

{% block content %}
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
<div class="container mt-3 ">
    {% for category, message in messages %}
    <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Sulge"></button>
    </div>
    {% endfor %}
</div>
{% endif %}
{% endwith %}
<div class="container mt-5">
    <div class="card shadow-lg">
        <div class="card-header custom-header text-white">
            <h2 class="card-title">Lisa uus osaühing ja osanikud</h2>
        </div>
        <div class="card-body">
            <form method="POST" class="needs-validation" novalidate>

                <!-- Firma nimi -->
                <div class="mb-3">
                    <label class="form-label fw-semibold">{{ form.name.label }}</label>
                    {{ form.name(class="form-control") }}
                    <small class="text-muted">3 kuni 100 tähte või numbrit.</small>

                    {% for error in form.name.errors %}
                    <div class="text-danger small">{{ error }}</div>
                    {% endfor %}
                </div>

                <!-- Registrikood -->
                <div class="mb-3">
                    <label class="form-label fw-semibold">{{ form.registry_code.label }}</label>
                    {{ form.registry_code(class="form-control") }}

                    {% for error in form.registry_code.errors %}
                    <div class="text-danger small">{{ error }}</div>
                    {% endfor %}
                </div>

                <!-- Asutamiskuupäev -->
                <div class="mb-3">
                    <label class="form-label fw-semibold">{{ form.established_date.label }}</label>
                    {{ form.established_date(class="form-control") }}

                    {% for error in form.established_date.errors %}
                    <div class="text-danger small">{{ error }}</div>
                    {% endfor %}
                </div>

                <!-- Kogukapital -->
                <div class="mb-3">
                    <label class="form-label fw-semibold">{{ form.capital.label }}</label>
                    {{ form.capital(class="form-control") }}
                    <small class="text-muted">Kogukapitali miinimum suurus on 2500€.</small>

                    {% for error in form.capital.errors %}
                    <div class="text-danger small">{{ error }}</div>
                    {% endfor %}
                </div>

                <h3 class="mt-4 custom-title">Osanikud</h3>

                <!-- Osanikke tabel -->
                <table class="table mt-4" id="shareholders-table">
                    <thead>
                    <tr>
                        <th>Osaniku tüüp</th>
                        <th>Eesnimi</th>
                        <th>Perekonnanimi</th>
                        <th>Ärinimi</th>
                        <th>Registrikood</th>
                        <th>Isikukood</th>
                        <th>Osa suurus (€)</th>
                        <th>Asutaja</th>
                        <th>Tegevused</th>
                    </tr>
                    </thead>
                    <tbody id="shareholders-body">

                    {% if form.shareholders %}
                    {% for shareholder in form.shareholders %}
                    <tr>
                        {{ shareholder.hidden_tag() }}
                        <td>
                            <select class="form-select shareholder-type" name="{{ shareholder.is_individual.name }}">
                                <option value="individual" {% if shareholder.is_individual.data==
                                'individual' %}selected{% endif %}>
                                Füüsiline isik
                                </option>
                                <option value="legal" {% if shareholder.is_individual.data==
                                'legal' %}selected{% endif %}>
                                Juriidiline isik
                                </option>
                            </select>
                        </td>
                        <td><input type="text" class="form-control" name="{{ shareholder.first_name.name }}"
                                   value="{{ shareholder.first_name.data or '' }}"
                                   {% if shareholder.is_individual.data !='individual' %}disabled{% endif %}>
                            {% for error in shareholder.first_name.errors %}
                            <div class="text-danger small">{{ error }}</div>
                            {% endfor %}
                        </td>
                        <td><input type="text" class="form-control" name="{{ shareholder.last_name.name }}"
                                   value="{{ shareholder.last_name.data or '' }}"
                                   {% if shareholder.is_individual.data !='individual' %}disabled{% endif %}>
                            {% for error in shareholder.last_name.errors %}
                            <div class="text-danger small">{{ error }}</div>
                            {% endfor %}
                        </td>
                        <td><input type="text" class="form-control" name="{{ shareholder.company_name.name }}"
                                   value="{{ shareholder.company_name.data or '' }}"
                                   {% if shareholder.is_individual.data !='legal' %}disabled{% endif %}>
                            {% for error in shareholder.company_name.errors %}
                            <div class="text-danger small">{{ error }}</div>
                            {% endfor %}
                        </td>
                        <td><input type="text" class="form-control" name="{{ shareholder.registry_code.name }}"
                                   value="{{ shareholder.registry_code.data or '' }}"
                                   {% if shareholder.is_individual.data !='legal' %}disabled{% endif %}>
                            {% for error in shareholder.registry_code.errors %}
                            <div class="text-danger small">{{ error }}</div>
                            {% endfor %}
                        </td>
                        <td><input type="text" class="form-control" name="{{ shareholder.personal_code.name }}"
                                   value="{{ shareholder.personal_code.data or '' }}"
                                   {% if shareholder.is_individual.data !='individual' %}disabled{% endif %}>
                            {% for error in shareholder.personal_code.errors %}
                            <div class="text-danger small">{{ error }}</div>
                            {% endfor %}
                        </td>
                        <td><input type="number" class="form-control" name="{{ shareholder.share.name }}"
                                   value="{{ shareholder.share.data }}"></td>
                        <td><input type="checkbox" name="{{ shareholder.is_founder.name }}"
                                   {% if shareholder.is_founder.data %}checked{% endif %}></td>
                        <td>
                            <button type="button" class="btn btn-danger btn-sm remove-row">Eemalda</button>
                        </td>
                    </tr>
                    {% endfor %}
                    {% endif %}
                    </tbody>


                </table>


                {% include "shareholder_form.html" %}

                <div class="mt-3">
                    {{ form.submit(class="save-button") }}
                </div>
            </form>
        </div>
    </div>
    <a href="{{ url_for('main.index') }}" class="btn btn-secondary mt-3">Tagasi avalehele</a>
</div>
<script src="{{ url_for('static', filename='js/shareholder_form.js') }}"></script>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Bootstrap Icons -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.5/font/bootstrap-icons.min.css"
          rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

    <!-- Bootstrap Bundle JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-dark">
        <div class="container">
            <!-- Logo ja nimi -->
            <a class="navbar-brand fw-bold" href="{{ url_for('main.index') }}">
                <i class="bi bi-building"></i> E-Registri Süsteem
            </a>

            <!-- Menüü lingid -->
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('main.index') }}">Avaleht</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('main.add_company') }}">Osaühingu asutamine</a>
                </li>
            </ul>

            <!-- Logi sisse nupp -->
            <button id="theme-toggle" class="login-button">Logi sisse</button>
        </div>
    </nav>
</header>

<main>
    {% block content %}{% endblock %}
</main>

<footer class="bg-light pt-4 border-top">
    <div class="container">
        <div class="row">
            <!-- Left Section -->
            <div class="col-md-4">
                <h6 class="fw-bold">Klienditugi</h6>
                <ul class="list-unstyled text-muted">
                    <li><i class="fa fa-envelope-open me-2 "></i><a href="mailto:info@rik.ee"
                                                                    class="text-decoration-none">info@rik.ee</a>
                    </li>
                    <li><i class="fa fa-phone-alt me-2 "></i>Telefon: <a href="tel:+3726803160"
                                                                         class="text-decoration-none">+372
                        +372 6543210</a></li>
                    <li><i class="fa fa-clock me-2 "></i>E-R 9.00-17.00</li>
                    <li><i class="fa fa-globe me-2 "></i><a href="https://www.rik.ee"
                                                            class="text-decoration-none" target="_blank">www.rik.ee</a>
                    </li>
                </ul>
            </div>

            <!-- Middle Section -->
            <div class="col-md-4">
                <h6 class="fw-bold">Leia kiirelt</h6>
                <ul class="list-unstyled text-muted">
                    <li><a href="#" class="text-decoration-none">Registriosakond</a></li>
                    <li><a href="#" class="text-decoration-none">Notarid</a></li>
                    <li><a href="#" class="text-decoration-none">e-kinnistusraamat</a></li>
                    <li><a href="#" class="text-decoration-none">Maksu- ja Tolliamet</a></li>
                </ul>
            </div>

            <!-- Right Section -->
            <div class="col-md-4">
                <h6 class="fw-bold">Kasulik</h6>
                <ul class="list-unstyled text-muted">
                    <li><a href="#" class="text-decoration-none">Hinnakiri</a></li>
                    <li><a href="#" class="text-decoration-none">Juristaitab.ee</a></li>
                    <li><a href="#" class="text-decoration-none">e-residentidele</a></li>
                    <li><a href="#" class="text-decoration-none">Uuenduste nimekiri</a></li>
                </ul>
            </div>
        </div>
        <div class="row mt-4">
            <div class="col-md-6 text-end">
                <img src="{{ url_for('static', filename='images/EL-logo.svg') }}" alt="EU Logo" width="100">
            </div>
        </div>
    </div>
</footer>
</body>
</html>

<!--<script>-->
<!--    const toggleButton = document.getElementById('theme-toggle');-->
<!--    toggleButton.addEventListener('click', () => {-->
<!--        document.body.classList.toggle('dark-mode');-->
<!--    });-->
<!--</script>-->

app/templates/company_details.html
{% extends "base.html" %}

{% block content %}
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
<div class="container mt-3">
    {% for category, message in messages %}
    <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Sulge"></button>
    </div>
    {% endfor %}
</div>
{% endif %}
{% endwith %}
<div class="container mt-3">
    <!-- Tegevused ja filtreerimine kaardis -->
    <div class="card custom-card-shareholders mb-4">
        <div class="card-body d-flex justify-content-between align-items-center">
            <!-- Vaadete nupud -->

            <div class="d-flex align-items-center">
                <h4> {{ company.name }} ({{ company.registry_code }})</h4>
            </div>
            <!-- Filtreeri ja muud tööriistad -->
            <div class="d-flex align-items-center">
                <button class="btn btn-outline-secondary me-2"><i class="bi bi-file-earmark-arrow-down"></i> PDF
                </button>
                <button class="btn btn-outline-secondary me-2"><i class="bi bi-file-earmark-spreadsheet"></i> XLSX
                </button>
                <button class="btn btn-outline-secondary" onclick="window.print()"><i class="bi bi-printer"></i> Prindi
                </button>
            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-md-6">
            <div class="card custom-card-shareholders">
                <div class="card-header custom-header-shareholders">
                    <h4>Üldinfo</h4>
                </div>
                <div class="card-body">
                    <div class="row mb-2">
                        <div class="col-6 text-muted">Registrikood</div>
                        <div class="col-6">{{ company.registry_code }}</div>
                    </div>
                    <div class="row mb-2">
                        <div class="col-6 text-muted">Õiguslik vorm</div>
                        <div class="col-6">Osaühing</div>
                    </div>
                    <div class="row mb-2">
                        <div class="col-6 text-muted">Viimati uuendatud</div>
                        <div class="col-6">...</div>
                    </div>
                    <div class="row mb-2">
                        <div class="col-6 text-muted">Kapital</div>
                        <div class="col-6">{{ company.total_capital }} €</div>
                    </div>
                    <div class="row mb-2">
                        <div class="col-6 text-muted">Asutamiskuupäev</div>
                        <div class="col-6">{{ company.established_date }}</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col-md-6">
            <div class="card custom-card-shareholders">
                <div class="card-header custom-header-shareholders">
                    <h4>Osanikud</h4>
                    <!-- Kinnita nupp -->
                    <div class="d-grid">
                        <a href="{{ url_for('main.edit_shareholders', company_id=company.id) }}" class="btn btn-primary">
                            <i class="bi bi-pencil"></i> Muuda
                        </a>
                    </div>
                </div>
                <div class="card-body">
                    {% if company.shareholders %}
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>Nimi</th>
                            <th>Osaniku tüüp</th>
                            <th>Isikukood / Registrikood</th>
                            <th>Osa suurus</th>
                            <th>Asutaja</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for shareholder in company.shareholders %}
                        <tr>
                            <td>{{ shareholder.first_name and shareholder.last_name and (shareholder.first_name ~ " " ~
                                shareholder.last_name) or shareholder.company_name }}
                            </td>
                            <td>
                                {% if shareholder.first_name and shareholder.last_name and not shareholder.company_name %}
                                Füüsiline isik
                                {% else %}
                                Juriidiline isik
                                {% endif %}
                            </td>
                            <td>{{ shareholder.personal_code or shareholder.registry_code }}</td>
                            <td>{{ shareholder.share }} €</td>
                            <td>{% if shareholder.is_founder %}Jah{% else %}Ei{% endif %}</td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    {% else %}
                    <p>Osanikke ei leitud.</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <a href="{{ request.referrer or url_for('main.index') }}" class="btn btn-secondary mt-3">Tagasi nimekirja</a>
</div>
{% endblock %}

app/templates/edit_shareholders.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
    <h4>Muutmine: {{ company.name }} ({{ company.registry_code }})</h4>
    <h5 class="text-muted">Kogukapital: {{ company.total_capital }} €</h5>
    <form method="POST">
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>Nimi</th>
                <th>Osaniku tüüp</th>
                <th>Isikukood / Registrikood</th>
                <th>Osa suurus</th>
                <th>Asutaja</th>
            </tr>
            </thead>
            <tbody id="shareholders-body">
            {% for shareholder in form.shareholders %}
            <tr>
                <!-- Nimi -->
                <td>
                    {{ shareholder.first_name and shareholder.last_name and
                    (shareholder.first_name ~ " " ~
                    shareholder.last_name) or
                    shareholder.company_name }}
                </td>

                <!-- Osaniku tüüp -->
                <td>
                    {% if shareholder.first_name and shareholder.last_name and not shareholder.company_name %}
                    Füüsiline isik
                    {% else %}
                    Juriidiline isik
                    {% endif %}
                </td>

                <!-- Isikukood / Registrikood -->
                <td>
                    {{ shareholder.personal_code if shareholder.personal_code else
                    shareholder.registry_code }}
                </td>

                <td><input type="number" value="{{ shareholder.share }}"
                           class="form-control"></td>
                <td><input type="checkbox" {% if shareholder.is_founder
                           %}checked{% endif %}></td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="mt-3">
            {{ form.submit(class="save-button") }}
        </div>
    </form>
    {% include "shareholder_form.html" %}
    <a href="{{ url_for('main.company_details', company_id=company.id) }}" class="btn btn-secondary mt-3">Tagasi</a>
</div>
<script src="{{ url_for('static', filename='js/shareholder_edit_form.js') }}"></script>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block content %}

{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
{% for category, message in messages %}
<div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Sulge"></button>
</div>
{% endfor %}
{% endif %}
{% endwith %}
<div class="container my-4">
    <!-- Title -->
    <div class="text-center mb-4">
        <h3 class="display-6">Osaühingute Otsing</h3>
    </div>
    <!-- Search Bar -->
    <div class="row mb-4">
        <div class="col-md-8 mx-auto">
            <form method="GET" action="{{ url_for('main.search') }}" class="input-group">
                <input type="text" name="q" class="form-control form-control-lg"
                       placeholder="Otsi nime või registrikoodi järgi">
                <button type="submit" class="btn btn-primary btn-lg">
                    <i class="bi bi-search"></i> Otsi
                </button>
            </form>
        </div>
    </div>

    <div class="text-center my-5">
        <a href="{{ url_for('main.add_company') }}" class="btn btn-lg btn-primary shadow rounded-pill px-5 py-3">
            <i class="bi bi-plus-circle-fill me-2"></i> Asuta Uus Osaühing
        </a>
        <p class="mt-3 text-muted">Alusta oma ettevõtte loomise protsessi vaid ühe klikiga!</p>
    </div>
</div>
{% endblock %}

app/templates/search.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-4">
    <h2 class="mb-4">Otsingutulemused</h2>

    <!-- Tegevused ja filtreerimine kaardis -->
    <div class="card shadow-sm mb-4">
        <div class="card-body d-flex justify-content-between align-items-center">
            <!-- Vaadete nupud -->
            <div></div>
            <div class="d-flex align-items-center">
                <select id="sortOptions" class="form-select d-inline w-auto me-2">
                    <option selected>Järjestus</option>
                    <option value="name_asc">Nimi (kasvav)</option>
                    <option value="name_desc">Nimi (kahanev)</option>
                    <option value="registry-asc">Registrikood (kasvav)</option>
                    <option value="registry-desc">Registrikood (kahanev)</option>
                    <option value="capital-asc">Kogukapital (kasvav)</option>
                    <option value="capital-desc">Kogukapital (kahanev)</option>
                </select>
                <button id="filter-button" class="btn btn-outline-secondary me-2"><i class="bi bi-funnel"></i> Filtreeri
                </button>
                <button id="pdf-button" class="btn btn-outline-secondary me-2"><i
                        class="bi bi-file-earmark-arrow-down"></i> PDF
                </button>

                <button id="print-button" class="btn btn-outline-secondary"><i class="bi bi-printer"></i> Prindi
                </button>
            </div>
        </div>
    </div>

    <!-- Otsingutulemuste kaardid -->
    {% if results %}
    <div class="row g-4" id="cardsContainer">
        {% for company in results %}
        <div class="col-md-6 col-lg-4 card-item">
            <div class="card res_card h-100 shadow-lg border-0 rounded-4">
                <div class="card-body p-4">
                    <h5 class="card-title text-primary fw-bold mb-3">
                        <a href="{{ url_for('main.company_details', company_id=company.id) }}"
                           class="text-decoration-none">
                            <strong>{{ company.name }}</strong>
                        </a>
                    </h5>
                    <ul class="list-unstyled mb-4">
                        <li class="mb-2"><i class="bi bi-hash"></i>Registrikood: <strong> {{ company.registry_code
                            }}</strong></li>
                        <li class="mb-2"><i class="bi bi-calendar-event"></i>Asutamiskuupäev: <strong> {{
                            company.established_date }}</strong></li>
                        <li><i class="bi bi-cash-stack"></i>Kogukapital: <strong> €{{ company.total_capital }}</strong>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <div class="alert alert-warning" role="alert">
        <i class="bi bi-exclamation-triangle"></i> Tulemusi ei leitud.
    </div>
    {% endif %}


    <a href="{{ url_for('main.index') }}" class="btn btn-secondary mt-4">
        <i class="bi bi-arrow-left"></i> Tagasi avalehele
    </a>
</div>
<script src="{{ url_for('static', filename='js/search.js') }}"></script>
{% endblock %}